library(htmltools)
playlisthtml <-
  c("<!DOCTYPE html>",
    "<html lang=\"en\">",
    "<head>",
    "<meta charset=\"UTF-8\">",
    "<title>HTML5 Audio Player</title>",
    "<style>",
    "#playlist{",
    "list-style: none;",
    "}",
    "#playlist li a{",
    "color:aqua;",
    "text-decoration: none;",
    "}",
    "#playlist .current-song a{",
    "color: navy",
    "}",
    "</style>",
    "</head>",
    "<body>",
    "<video src=\"\" controls id=\"videoPlayer\" autoplay=\"autoplay\">",
    "Sorry, your browser doesn't support html5!",
    "</video>",
    "<ul id=\"playlist\">",
    # paste0("<li><a href=\"https://s3.amazonaws.com/publicuncsynergyvideo/PlaylistTest/", c(1:10), ".mp4\">Test Video ", c(1:10), "</a></li>"),
    sapply(c(1:10), function(x)as.character(tags$li(tags$a(x, href = paste0("https://s3.amazonaws.com/publicuncsynergyvideo/PlaylistTest/", x, ".mp4"))))),#tags$li()
    "</ul>",
    "<script src=\"https://code.jquery.com/jquery-2.2.0.js\">",
    "</script>",
    "<script>",
    "videoPlayer();",
    "function videoPlayer() {",
    "var currentSong = 0;",
    "$(\"#videoPlayer\")[0].src = $(\"#playlist li a\")[0];",
    "$(\"#videoPlayer\")[0].play();",
    "$(\"#playlist li a\").click(function(e){",
    "e.preventDefault();",
    "$(\"#videoPlayer\")[0].src = this;",
    "$(\"#videoPlayer\")[0].play();",
    "$(\"#playlist li\").removeClass(\"current-song\");",
    "currentSong = $(this).parent().index();",
    "$(this).parent().addClass(\"current-song\");",
    "});",
    "$(\"#videoPlayer\")[0].addEventListener(\"ended\", function(){",
    "currentSong++;",
    "if(currentSong == $(\"playlist li a\").length)",
    "currentSong = 0;",
    "$(\"#playlist li\").removeClass(\"current-song\");",
    "$(\"#playlist li:eq(\"+currentSong+\")\").addClass(\"current-song\");",
    "$(\"#videoPlayer\")[0].src = $(\"#playlist li a\")[currentSong].href;",
    "$(\"videoPlayer\")[0].play();",
    "});",
    "}",
    "</script>",
    "</body>",
    "</html>")
write(playlisthtml, file = "TestPlaylist.html")

crosstalk::bscols(widths = c(6, 6),
                  tags$iframe("Metzdorf_LHH_K.html"), tags$iframe("Metzdorf_LHH_XBH.html"),
                  tags$iframe("Metzdorf_RHH_K.html"), tags$iframe("Metzdorf_RHH_XBH.html")
)


